# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 22:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rater',
            name='name',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rater',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='rater',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='rater',
            name='occupation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rater',
            name='zip_code',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
