# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 23:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_auto_20160328_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=6, null=True)),
                ('age', models.CharField(max_length=3)),
                ('occupation', models.CharField(max_length=150)),
                ('zip_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='rating',
            name='date_modified',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AddField(
            model_name='movie',
            name='rater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.Rater'),
        ),
    ]
