# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_auto_20160328_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date_modified',
        ),
    ]
