# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_remove_movie_date_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.AddField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.Rater'),
        ),
    ]
